### PR TITLE
Visualizer: Fix showing of zoomOutButton

### PR DESCRIPTION
**Pull request by lilyx**
Bug fix: zoomOutButton should hide when there is no zoomState

### CODE REVIEW

**Comment by mroeder** [comment]
I couldn't reproduce any bug around that in the current `master` but it's LGTM.

**Comment by lilyx** [comment]
Try change the example under zoom mode, the zoom out button will left there.

**Comment by mroeder** [comment]
Gotcha! Still LGTM. You should merge it. :-)

**Comment by pdubroy** [comment]
I haven't looked but please feel free to merge with Marko's lgtm :-)

**Pull request merged**
